// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bjUV2PxdTQInCdhFNaGA6XUSIVpnkWk',
    appId: '1:542063716062:web:f011c44bd17945346f844f',
    messagingSenderId: '542063716062',
    projectId: 'well-15762',
    authDomain: 'well-15762.firebaseapp.com',
    storageBucket: 'well-15762.appspot.com',
    measurementId: 'G-M6G6W5234G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXN0v-YHzUplWwqGJugI7UbkdhvfA6kNA',
    appId: '1:542063716062:android:66e02a1785b31d716f844f',
    messagingSenderId: '542063716062',
    projectId: 'well-15762',
    storageBucket: 'well-15762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xodstRgQrOmHv6OlBBTpW3krwDR4lTM',
    appId: '1:542063716062:ios:f8bc451420f284a96f844f',
    messagingSenderId: '542063716062',
    projectId: 'well-15762',
    storageBucket: 'well-15762.appspot.com',
    androidClientId: '542063716062-a29fhsfhfs1i790das2qjlosopon7n0r.apps.googleusercontent.com',
    iosClientId: '542063716062-md30guen4iqj7j5gp5eeon6a5j9k9e2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2xodstRgQrOmHv6OlBBTpW3krwDR4lTM',
    appId: '1:542063716062:ios:9e7363bb3cd215ff6f844f',
    messagingSenderId: '542063716062',
    projectId: 'well-15762',
    storageBucket: 'well-15762.appspot.com',
    androidClientId: '542063716062-a29fhsfhfs1i790das2qjlosopon7n0r.apps.googleusercontent.com',
    iosClientId: '542063716062-dn5dn80catrfl1kbi8dulv2ngc52hg5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapk.RunnerTests',
  );
}
